version: '3.8'

services:
  go-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  nextjs-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      NODE_ENV: production
    command: npm start

networks:
  app-network:
    driver: bridge
