// pages/index.js
"use client";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import NavBar from "./navbar";
import { useEffect, useState } from "react";
import { callApi } from "@/app/utils/api-utils";

export default function Main() {
  const [token, setToken] = useState(null);

  useEffect(() => {
    setToken(localStorage ? localStorage?.getItem("access_token") : null);
    try {
      async function ValidateToken() {
        const response = await callApi(
          process.env.NEXT_PUBLIC_TOKEN_VALIDATE,
          {},
          "GET"
        );
        if (response) {
          if (response.status != 200) {
            localStorage.clear();
            window.location.reload();
          }
        }
      }
      if (localStorage?.getItem("access_token")) {
        ValidateToken();
      }
    } catch (error) {
      console.log("error in checking auth home ", error);
    }
  }, []);

  async function ValidateToken() {
    const response = await callApi(
      process.env.NEXT_PUBLIC_TOKEN_VALIDATE,
      {},
      "GET"
    );
    if (response) {
      if (response.status != 200) {
        localStorage.clear();
        window.location.reload();
      }
    }
  }

  return (
    <>
      {!token ? (
        <>
          <Head>
            <title>Travel Itinerary Generator</title>
          </Head>

          <nav className="flex justify-between items-center p-4 shadow-md bg-black text-white">
            {/* <div> */}
            {/* <Image
            src={"/travel.png"}
            alt="Travel destination"
            // layout="fill"
            // objectPosition="center"
            width={60}
            height={60}
            // className="border-r-4"
            style={{ borderRadius: "50%" }}
          /> */}
            <h1 className="text-xl font-bold">Travel Itinerary Generator</h1>
            {/* </div> */}
            <div>
              <Link href="/user/login">
                <span className="text-blue-500 hover:text-blue-700 px-4">
                  Login
                </span>
              </Link>
              <Link href="/user/signup">
                <span className="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded">
                  Signup
                </span>
              </Link>
            </div>
          </nav>
        </>
      ) : (
        <NavBar color={true} />
      )}
      <main className="flex flex-col items-center justify-center p-8 bg-black text-white">
        <section className="text-center">
          <h2 className="text-5xl font-bold mt-0 mb-6">
            Professional AI Travel Plans in Minutes
          </h2>
          <p className="mb-4">
            Elevate your journey with personalized itineraries generated by our
            AI. Ideal for exploring new destinations and building lasting
            memories.
          </p>
          {!token ? (
            <Link href="/user/login">
              <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-full mb-6 transition duration-300 ease-in-out">
                Get Your Itinerary
              </button>
            </Link>
          ) : (
            <Link href="/dashboard" onClick={ValidateToken}>
              <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-full mb-6 transition duration-300 ease-in-out">
                Get Your Itinerary
              </button>
            </Link>
          )}
          <p className="text-gray-600">
            Trusted by nomads and travelers worldwide. Quick and efficient.
          </p>
          {/* <Link href="/signin">
            <span className="text-blue-500 hover:text-blue-700">
              Already a member? Sign In
            </span>
          </Link> */}
        </section>

        <div className="w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 mt-8">
          <div className="w-full h-64 relative bg-gray-300 rounded-lg shadow-md overflow-hidden">
            <Image
              src={"/two.jpg"}
              alt="Travel destination"
              layout="fill"
              objectPosition="center"
            />
          </div>
          <div className="w-full h-64 relative bg-gray-300 rounded-lg shadow-md overflow-hidden">
            <Image
              src={"/one.jpg"}
              alt="Travel destination"
              layout="fill"
              objectPosition="center"
            />
          </div>
          <div className="w-full h-64 relative bg-gray-300 rounded-lg shadow-md overflow-hidden">
            <Image
              src={"/three.jpg"}
              alt="Travel destination"
              layout="fill"
              objectPosition="center"
            />
          </div>
          <div className="w-full h-64 relative bg-gray-300 rounded-lg shadow-md overflow-hidden">
            <Image
              src={"/four.jpg"}
              alt="Travel destination"
              layout="fill"
              objectPosition="center"
            />
          </div>
          <div className="w-full h-64 relative bg-gray-300 rounded-lg shadow-md overflow-hidden">
            <Image
              src={"/five.jpg"}
              alt="Travel destination"
              layout="fill"
              objectPosition="center"
            />
          </div>
          <div className="w-full h-64 relative bg-gray-300 rounded-lg shadow-md overflow-hidden">
            <Image
              src={"/six.jpg"}
              alt="Travel destination"
              layout="fill"
              objectPosition="center"
            />
          </div>
        </div>
      </main>
      <footer className="bg-gray-800 text-gray-400 body-font">
        <div className="container px-3 py-3 mx-auto flex items-center sm:flex-row flex-col">
          <div className="flex title-font font-medium items-center md:justify-start justify-center text-white ">
            {/* Add your logo img tag or text here */}
            <Image
              src={"/travel.png"}
              alt="Travel destination"
              // layout="fill"
              // objectPosition="center"
              width={60}
              height={60}
              // className="border-r-4"
              style={{ borderRadius: "50%" }}
            />
            <span className="ml-3 text-xl">Travel Itinerary Generator</span>
          </div>
          <p className="text-sm sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">
            © {new Date().getFullYear()} Travel Itinerary Generator —
            <a
              href="https://twitter.com/knyttneve"
              className="text-gray-500 ml-1"
              rel="noopener noreferrer"
              target="_blank"
            >
              @Vijay Bhati
            </a>
          </p>
          <span className="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
            <a className="text-gray-400">{/* Add social icons as needed */}</a>
            <a
              className="ml-3 text-gray-400 cursor-pointer"
              href="https://github.com/vj98"
              target="_blank"
            >
              <span className="[&>svg]:h-7 [&>svg]:w-7 [&>svg]:fill-[#fcfcfc]">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512">
                  <path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3 .3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5 .3-6.2 2.3zm44.2-1.7c-2.9 .7-4.9 2.6-4.6 4.9 .3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3 .7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3 .3 2.9 2.3 3.9 1.6 1 3.6 .7 4.3-.7 .7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3 .7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3 .7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z" />
                </svg>
              </span>
            </a>
            <a
              className="ml-3 text-gray-400"
              href="https://twitter.com/bhati_vijay17"
              target="_blank"
            >
              <span className="[&>svg]:h-7 [&>svg]:w-7 [&>svg]:fill-[#fcfcfc]">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="currentColor"
                  viewBox="0 0 512 512"
                >
                  <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z" />
                </svg>
              </span>
            </a>
          </span>
        </div>
      </footer>
    </>
  );
}
